name: locator_for_perception
description: A simple service locator used in perception packages.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test: ^1.24.9
