name: astro_locator
description: A simple service locator used in astro packages.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
